### ISSUE TITLE
css conversion error with github pages

### ISSUE THREAD

**Issue by calum-chamberlain** [jeffreytse/jekyll-theme-yat#173]
I'm after some help with an error that I'm running into when trying to build for github-pages:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid CSS after "...in-bottom: math": expected ";", was ".div($spacing-u..." on line 45

```
This seems to stem from one of the yat theme css files [here](https://github.com/jeffreytse/jekyll-theme-yat/blob/6b376ec37866214b42d8ae78003447b136e165b5/_sass/yat/_base.scss#L45) and possibly others from the recent [commit](https://github.com/jeffreytse/jekyll-theme-yat/commit/6b376ec37866214b42d8ae78003447b136e165b5):
```
/tmp/jekyll-remote-theme-20241013-12540-3ng7gr/_sass/yat/_base.scss:45: Invalid CSS after "...in-bottom: math": expected ";", was ".div($spacing-u..." (Sass::SyntaxError)
```

Apologies if this isn't the source of the error - I think that github pages requires quite an old version of the jekyll-css-converter (I have 1.5.2 installed) which might be in conflict with this deprecation.

Happy to provide more details and post the gemfile as needed. All the files I'm using are [here](https://github.com/SeismicCycleRacing/SCR-blog). 

Thanks!

**Comment by jeffreytse** [comment]
Hi @calum-chamberlain,

Could you update to the latest version of YAT? It's better to use the git upstream version. I believe it's caused by a lower version of Jekyll.

Thanks & Regards

**Comment by calum-chamberlain** [comment]
Hi @jeffreytse - thanks for that, and please excuse my ignorance, but I thought I was using the git upstream version so I think I must be doing something wrong. At the moment I have `remote_theme: "jeffreytse/jekyll-theme-yat"` in my [_config.yml](https://github.com/SeismicCycleRacing/SCR-blog/blob/main/_config.yml) file. 

It looks like I'm running Jekyll 3.9.5 for this (output for `bundle exec jekyll --version`).

**Comment by calum-chamberlain** [comment]
Running with ` remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"` seems to work fine.

**Comment by jeffreytse** [comment]
@calum-chamberlain You're welcome! For the upstream version, it should work. To solve the problem, I suggest you to use [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) instead.

**Comment by jeffreytse** [comment]
@calum-chamberlain @sternrest Now you can try the latest version. With this commit ed515492e77a0e419b58d8da2fc13c2dae8ab362, you can build the site normally. : )

**Comment by calum-chamberlain** [comment]
That hasn't worked for me. I still get a css conversion issue with github pages:
```ruby
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid CSS after " @if meta": expected "{", was ".function-exist..." on line 72
jekyll 3.9.5 | Error:  Invalid CSS after "  @if meta": expected "{", was ".function-exist..." on line 72
/home/chambeca/gems/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid CSS after "  @if meta": expected "{", was ".function-exist..." on line 72 (Jekyll::Converters::Scss::SyntaxError)

        raise SyntaxError, "#{e} on line #{e.sass_line}"
```

I'm happy to pin my build to the commit before the divide updates until I get around to using the jekyll-deploy-action.

**Comment by jr-dev1001** [comment]
I'm dealing with the same problem as you.

`
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid CSS after " @if meta": expected "{", was ".function-exist..." on line 72
/usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid CSS after "  @if meta": expected "{", was ".function-exist..." on line 72 (Jekyll::Converters::Scss::SyntaxError)
        raise SyntaxError, "#{e} on line #{e.sass_line}"
`

**Comment by cvillecsteele** [comment]
Same issue here.

**Comment by jeffreytse** [comment]
As Jekyll 3.x does not support `jekyll-sass-converter 2.0`, the older version of `jekyll-sass-converter 1.5.2` doesn't support a lot of built-in functions, especially functions in `meta` module. Could you try to upgrade your Jekyll version to 4.X as this project's action for test.

Please see here: https://github.com/jeffreytse/jekyll-theme-yat/actions/runs/11436937614/job/31815433529

![image](https://github.com/user-attachments/assets/8c9dc494-3b91-4842-8fa4-2230588ab265)

**Comment by jeffreytse** [comment]
As the `github-pages` gem requires the `3.X.X` version, I've updated the instructions for using remote theme. Please refer to [here](https://github.com/jeffreytse/jekyll-theme-yat?tab=readme-ov-file#remote-theme-method-with-jekyll-remote-theme-plugin) to replace your `github-pages` gem, and then update your dependencies by command `bundle update`.
